version: '3.7'
services:
  wolweb:
    image: wolweb:latest
    container_name: wolweb
    # Use environment variable below to change port or virtual directory.
    #environment:
      #WOLWEBPORT: "8089"
      #WOLWEBVDIR: "/wolweb"
      #WOLWEBBCASTIP: "192.168.1.255:9"
    volumes:
      - /data/wolweb:/wolweb/data # binding required for persistent data
    network_mode: host # host mode required to support WoL Magic Packets
